create table if not exists public.pm_users (
  source_slug text not null default 'yougile',
  external_id text not null,
  name text,
  email text,
  is_active boolean not null default true,
  raw jsonb not null default '{}'::jsonb,
  synced_at timestamptz not null default now(),
  primary key (source_slug, external_id)
);

create table if not exists public.pm_projects (
  source_slug text not null default 'yougile',
  external_id text not null,
  title text,
  is_archived boolean not null default false,
  raw jsonb not null default '{}'::jsonb,
  synced_at timestamptz not null default now(),
  primary key (source_slug, external_id)
);

create table if not exists public.pm_boards (
  source_slug text not null default 'yougile',
  external_id text not null,
  project_external_id text,
  title text,
  is_archived boolean not null default false,
  raw jsonb not null default '{}'::jsonb,
  synced_at timestamptz not null default now(),
  primary key (source_slug, external_id)
);

create index if not exists pm_boards_project_idx on public.pm_boards (source_slug, project_external_id);

create table if not exists public.pm_columns (
  source_slug text not null default 'yougile',
  external_id text not null,
  board_external_id text,
  title text,
  position integer,
  is_archived boolean not null default false,
  raw jsonb not null default '{}'::jsonb,
  synced_at timestamptz not null default now(),
  primary key (source_slug, external_id)
);

create index if not exists pm_columns_board_idx on public.pm_columns (source_slug, board_external_id);

create table if not exists public.pm_tasks (
  source_slug text not null default 'yougile',
  external_id text not null,
  title text,
  project_external_id text,
  board_external_id text,
  column_external_id text,
  assigned_user_external_ids text[] not null default '{}'::text[],
  deadline_at timestamptz,
  completed boolean not null default false,
  is_archived boolean not null default false,
  created_at_source timestamptz,
  updated_at_source timestamptz,
  raw jsonb not null default '{}'::jsonb,
  synced_at timestamptz not null default now(),
  primary key (source_slug, external_id)
);

create index if not exists pm_tasks_project_idx on public.pm_tasks (source_slug, project_external_id);
create index if not exists pm_tasks_column_idx on public.pm_tasks (source_slug, column_external_id);
create index if not exists pm_tasks_deadline_idx on public.pm_tasks (source_slug, deadline_at);

create table if not exists public.pm_task_stage_events (
  id bigint generated by default as identity primary key,
  source_slug text not null default 'yougile',
  task_external_id text not null,
  project_external_id text,
  board_external_id text,
  column_external_id text,
  observed_at timestamptz not null default now()
);

create index if not exists pm_task_stage_events_task_idx on public.pm_task_stage_events (source_slug, task_external_id, observed_at);
create index if not exists pm_task_stage_events_column_idx on public.pm_task_stage_events (source_slug, column_external_id, observed_at);

insert into public.data_sources (slug, name, category, connection_mode, status)
values ('yougile', 'YouGile', 'Производство', 'edge', 'not_configured')
on conflict (slug) do update set
  name = excluded.name,
  category = excluded.category,
  connection_mode = excluded.connection_mode;

alter table public.pm_users enable row level security;
alter table public.pm_projects enable row level security;
alter table public.pm_boards enable row level security;
alter table public.pm_columns enable row level security;
alter table public.pm_tasks enable row level security;
alter table public.pm_task_stage_events enable row level security;
